/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class invoke */

#ifndef _Included_invoke
#define _Included_invoke
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     invoke
 * Method:    print_jni
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_invoke_print_1jni
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
